### ISSUE TITLE
geany crashes when geanypy is activated an libpython is not installed

### ISSUE THREAD

**Issue by Akronix** [codebrainz/geanypy#20]
Hi!

I've re-installed Ubuntu 15.04 (just the system I preserved my home folder and apps configuration).
When It tried to run Geany I got this error:

    ** (geany:1842): WARNING **: Unable to pre-load Python library: /usr/lib/x86_64-linux-gnu/libpython2.7.so: cannot open shared object file: No such file or directory.
    [1]    1842 segmentation fault (core dumped)  geany

I found out after a time that it was because of python-dev dependency.
[I know all the dependencies are well listed in your web](http://codebrainz.github.io/geanypy/): python python-dev python-gtk2 python-gtk2-dev ; Nevertheless, wouldn't be a good idea to detect these dependencies and show them or install them instead of throwing that error?

**Comment by elextr** [comment]
How did you install Geany? 

 The configure step in a build-from-source checks for Python and disable geanypy if its not found.

The install steps used by packages are part of the packages, we don't define them, so you would need to report it to the packagers.

Geany would have difficulty checking for Python at runtime since we don't explicitly load the Python library I don't think, we have linked to it (or at least Geanypy has).

**Comment by Akronix** [comment]
I installed it through the Ubuntu official repo.

it hasn't to be at runtime, simply the _geany-plugin-py_ package could add a depency against _python-dev_ package and this would be solved. Then yes, I guess it's packager's fault.

**Comment by codebrainz** [comment]
@elextr it actually does open the lib at runtime. The place where that message is coming from is here:

https://github.com/codebrainz/geanypy/blob/master/src/geanypy-plugin.c#L71

It had to be added because of some issue that was experienced with Python's module loader and how it loaded extension modules or something. It might've simply been a bug in Python or GeanyPy that has since been fixed. It might be worth investigating further now, some years later.

But either way, it should find it, it looks for the one it linked against at compile time. It even shouldn't require `python-dev` package unless you're compiling GeanyPy.

**Comment by elextr** [comment]
@codebrainz I did say "I don't think" :)

So there are several parts to the problem 

1) GeanyPy shouldn't be installed if Python 2 isn't available so Geany won't load it, so it won't try to look for Python.

2) the line you point to uses a path generated by configure, so its the path on the build machine, not the install machine, which *should* be the same for distro specific packages but...

3) GeanyPy shouldn't *CRASH*, it correctly detects it can't load Python, so it should politely decline to do anything from there on.

**Comment by codebrainz** [comment]
@elextr for 3) ideally Geany would allow plugins to tell it if they could initialize properly, but since it doesn't I guess the only thing to do is to put a `return` [here](https://github.com/codebrainz/geanypy/blob/master/src/geanypy-plugin.c#L80). Though that's likely just to cause a crash later on down the line.

In a perfect world we could figure out the source of the original problem and fix it so we could remove this "hack", then we don't care about the path to libpython, it's all the runtime loader's problem. Lots of programs and libraries embed libpython, I wonder how they solve this issue, or if they even see it. The only "weird" thing is that GeanyPy is itself a "module" and not a program or typical shared lib.

**Comment by elextr** [comment]
> @elextr for 3) ideally Geany would allow plugins to tell it if they could initialize properly, 

Yes, that would be good.

>  Though that's likely just to cause a crash later on down the line.

Isn't that whats happening? The plugin takes the return after the g_warning() and since something is not set up it gets a segfault later.  

As you suggest above, disabling plugins that signal failure would remove the requirement for redundant checks "am I initialized correctly?" throughout plugins.  Such checks are bad because they are easily forgotten and can affect performance.

But the underlying problem is still that the package allows the plugin package to be installed when some dependency is not available.  Thats what packages are meant to prevent.  (Or the package was configured wrongly and is looking in the wrong place for the Python).

> The only "weird" thing is that GeanyPy is itself a "module" and not a program or typical shared lib.

Yes but the loader is supposed to load dependencies, to quote from dlopen's docs "If the library has dependencies on other shared libraries, then these are also automatically loaded by the dynamic linker using the same rules. (This process may occur recursively, if those libraries in turn have dependencies, and so on.)" so maybe it something about how the Python library is loaded, for example maybe the Python library does not put its symbols in the global scope by default (ie no RTLD_GLOBAL).

**Comment by robblue2x** [comment]
I had this error and fixed it by making a like like this:
sudo ln -s /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 /usr/lib/x86_64-linux-gnu/libpython2.7.so

geanypy looks for libpython2.7.so which didn't exist on my system, but adding that symlink lets it load with no problems

**Comment by elextr** [comment]
> > @elextr for 3) ideally Geany would allow plugins to tell it if they could initialize properly,

> Yes, that would be good.

There is a new plugin interface coming "real soon now" that will allow this.

**Comment by codebrainz** [comment]
> geanypy looks for libpython2.7.so which didn't exist on my system, but adding that symlink lets it load with no problems

Good tip. I have a similar symlink here, though I don't think I had to add it manually (Ubuntu 15.04).

**Comment by robblue2x** [comment]
> Good tip. I have a similar symlink here, though I don't think I had to add it manually (Ubuntu 15.04).
I didn't have to make that symlink on my laptop, or my work laptop. All my machines running Xubuntu 15.04, work laptop running 14.04. There must have been an error when I installed on my PC

**Comment by Akronix** [comment]
I think that symlink is automatically generated when libpython2.7 is installed. I don't think that link works if you haven't got that package though.
 >>> @elextr for 3) ideally Geany would allow plugins to tell it if they could initialize properly,

 >> Yes, that would be good.

> There is a new plugin interface coming "real soon now" that will allow this.

Something like that sounds really good :smiley:

**Comment by evgeni** [comment]
Let's revive this issue to it can finally be fixed at some point ;-)

This has been reported in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778552 and I can reproduce the issue when libpython2.7-dev (which carries the symlink) is not installed.

When I drop the rather weird code at https://github.com/codebrainz/geanypy/blob/master/src/geanypy-plugin.c#L71, the plugin does not work and only yields the following in the terminal:

    (geany:6114): GLib-CRITICAL **: g_string_truncate: assertion 'string != NULL' failed
    ImportError: could not import gobject (error was: '/usr/lib/libpyglib-2.0-python2.7.so.0: undefined symbol: _Py_ZeroStruct')
    ImportError: No module named geany
    
    ** (geany:6114): WARNING **: Unable to import 'geany' module
    
    ** (geany:6114): WARNING **: Failed to import manager module
    
    (geany:6114): GLib-CRITICAL **: g_string_truncate: assertion 'string != NULL' failed
    
    ** (geany:6114): CRITICAL **: GeanyPy_show_manager: assertion 'manager != NULL' failed
    
    ** (geany:6114): CRITICAL **: signal_manager_free: assertion 'man != NULL' failed

As geanypy.so itself is actually linked against libpython2.7.so.1.0, why don't we memorize *that* name instead of the generic libpython2.7.so?

**Comment by codebrainz** [comment]
> When I drop the rather weird code at [...]

I believe the reason for that weird code is what this bug is about:

http://bugs.python.org/issue4434

It took me many hours of debugging and research to find a solution, which is why I have left that weird code in place, although it's possible that it's not required anymore with newer Python/Ubuntu combos.
