### ISSUE TITLE
Sync with Geany-Plugins?

### ISSUE THREAD

**Issue by eht16** [codebrainz/geanypy#41]
What's the plan about keeping this in sync with the copy of GeanyPy in the Geany-Plugins project?
It seems a few commits here are missing in Geany-Plugins (https://github.com/codebrainz/geanypy/commit/b71408716bda9575c6222113edd1c4b96d4f9765, https://github.com/codebrainz/geanypy/commit/bbfb92926b3526a8f3a71ea11677d3cfb7ea8706, maybe more).
Recently, https://github.com/codebrainz/geanypy/commit/d11b4eb761b43b6e727690dedf7e401908770da5 was merged but in Geany-Plugins the same fix was committed with a different hash from a different commit.

I'd wish both repos were in sync.

**Comment by codebrainz** [comment]
They could be in sync if Geany-Plugins was using Git submodules, and we had a way to have both a standalone Autotools build system as well as the Geany-Plugins one. The way it is now, the maintainer of the GeanyPy fork in Geany-Plugins is required to manually keep them in sync.

**Comment by eht16** [comment]
Hmm ok. I hoped we'll get something more integrated. It's a bit a pity to see the repos are somewhat out of sync.

Who exactly is "the maintainer of the GeanyPy fork in Geany-Plugins"? @frlan @kugel ?

**Comment by elextr** [comment]
@eht16 geanypy in Geany-Plugins is a bit unusual for historical reasons.  It is not an independent plugin development, as its docs say, its a copy of this upstream with the build system changed to fit with G-P.

I made it the G-P version because @codebrainz wasn't willing/able to do the build system changes at the time.  I put myself as maintainer of the G-P plugin since it would have been rude to nominate somebody else without their consent.  And nobody else has offered to take over since ;)  But of course its not intended that it be independently maintained separate from upstream anyway.

The intention is that things only get taken from upstream to the downstream G-P plugin when they were accepted here.  But its always possible that things have been missed :)

The major changes in #37  have not yet been accepted by @codebrainz and even if he had I don't have the time at the moment to make the PR on G-P.  But having been involved in its evolution its fine with me if @kugel- makes the PR on G-P, its an important upgrade and we warned about it on the geanypy plugin README (and so the website) at the 1.26 release.

**Comment by eht16** [comment]
Ok, it's fine with me if the G-P version is a bit behind the upstream here and if we have a maintainer, you, which is aware of all this. I was not, sorry.

I fully understand #37 is a heavy one and might not be merged directly, this is ok.

What about the mentioned commits above (https://github.com/codebrainz/geanypy/commit/b71408716bda9575c6222113edd1c4b96d4f9765, https://github.com/codebrainz/geanypy/commit/bbfb92926b3526a8f3a71ea11677d3cfb7ea8706) and maybe more from the past which seem not to be merged?
I don't talk about merging for 1.27 but maybe afterwards so they don't get lost.

**Comment by elextr** [comment]
Yeah, it should be reviewed, I know @codebrainz directly committed some things to G-P but that was some time ago, and as I said in #37 I thought he had an auto-updater script so I wasn't watching so carefully, but that script is for another of his plugins.  So its entirely possible things have been missed.
